services:
  backend:
    image: ghcr.io/zethange/echogram:latest
    restart: unless-stopped
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - db
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.echogram_backend.rule=Host(`echogram.zethange.ru`)"
      - "traefik.http.routers.echogram_backend.entrypoints=web"
      - "traefik.http.services.echogram_backend.loadbalancer.server.port=8080"

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    networks:
      - default
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

networks:
  web:
    external: true
  default: