spring:
  application:
    name: 'Secgram'

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:secgram}
    username: ${DB_USERNAME:demo}
    password: ${DB_PASSWORD:demo}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    token: ${JWT_KEY:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855}

  main:
    allow-circular-references: true